/* Generated by Makefile.win32.  Do not edit. */
#ifndef CAIRO_FEATURES_H
#define CAIRO_FEATURES_H 1
#define CAIRO_HAS_PNG_FUNCTIONS 1
#define CAIRO_HAS_IMAGE_SURFACE 1
#define CAIRO_HAS_META_SURFACE 1
#endif
